name: crop-yield-forecasting
channels:
- conda-forge
dependencies:
- pip

#### General science packages
- pandas
- numpy
- datetime
- re
- jupyter
- dload

#### Statistics 
- scipy
- statsmodels.api
- sklearn

#### Geospatial packages
- ee
- eemont
- geopandas
- rasterio
- rioxarray
- xarray
- shapely

#### Visualisation
- matplotlib
- folium
- seaborn